TOWHIDcv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('enroll/', include('signup_user.urls')),

    # app section
    path('password_generator/', include('app.pass_gen.urls')),
    path('food-app', include('app.food.urls')),
    path('todo/', include('app.todo.urls')),

    # game section
    path('tic-tac-toe', include('game.tic_tac_toe.urls')),
    path('rock-paper-scissors', include('game.rock_paper_scissors.urls')),
    
    # web section
    path('photo-gallery/', include('web.photo_gallery.urls')),
    path('ecommerce/', include('web.ecommerce.urls')),
    path('blog/', include('web.blog.urls')),

    # local
    path('education/', include('education.urls')),

    # Extra
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # app section -- api
    # path('api-auth/', include('rest_framework.urls')),
    path('api/todo/', include('app.todo.api.urls')),
]
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index")
]

web/photo_gallery/urls.py
from django.urls import path
from . import views

app_name = 'photo_gallery'
urlpatterns = [
    path('', views.gallery, name="photo_gallery"),
    path('post/<slug:slug>', views.details, name="post")
]

web/photo_gallery/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.

class AddImage(models.Model):
    title = models.CharField(max_length=100)
    image = models.CharField(max_length=500)
    content = RichTextField()
    slug = models.SlugField(unique=True, null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    edited = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwarge):
        from . helpers import generate_slug
        self.slug = generate_slug(self.title)
        super(AddImage, self).save(*args, **kwarge)

web/photo_gallery/views.py
from django.shortcuts import render
from . models import AddImage

# Create your views here.

def gallery(request):
    all_img = AddImage.objects.all()
    return render(request, 'photo_gallery/index.html', {
        'all_post': all_img
    })

def details(request, slug):
    post = AddImage.objects.get(slug = slug)
    random_p = AddImage.objects.order_by('?')[0:10]
    return render(request, 'photo_gallery/post.html',{
        'post': post,
        'random': random_p
    })

web/photo_gallery/templates/photo_gallery/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home - Pintereso Bootstrap Template</title>
    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
    <link rel="stylesheet" href="{% static 'photo_gallery/assets/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'photo_gallery/assets/css/theme.css' %}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <a class="navbar-brand font-weight-bolder mr-3" href="index.html"><img src="{% static 'photo_gallery/assets/img/logo.png' %}"></a>
    <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsDefault" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsDefault">
        <ul class="navbar-nav mr-auto align-items-center">
            <form class="bd-search hidden-sm-down">
                <input type="text" class="form-control bg-graylight border-0 font-weight-bold" id="search-input" placeholder="Search..." autocomplete="off">
                <div class="dropdown-menu bd-search-results" id="search-results">
                </div>
            </form>
        </ul>
        <ul class="navbar-nav ml-auto align-items-center">
            <li class="nav-item">
            <a class="nav-link active" href="/">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="post.html">Post</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="author.html"><img class="rounded-circle mr-2" src="{% static 'photo_gallery/assets/img/av.png' %}" width="30"><span class="align-middle">Author</span></a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg style="margin-top:10px;" class="_3DJPT" version="1.1" viewbox="0 0 32 32" width="21" height="21" aria-hidden="false" data-reactid="71"><path d="M7 15.5c0 1.9-1.6 3.5-3.5 3.5s-3.5-1.6-3.5-3.5 1.6-3.5 3.5-3.5 3.5 1.6 3.5 3.5zm21.5-3.5c-1.9 0-3.5 1.6-3.5 3.5s1.6 3.5 3.5 3.5 3.5-1.6 3.5-3.5-1.6-3.5-3.5-3.5zm-12.5 0c-1.9 0-3.5 1.6-3.5 3.5s1.6 3.5 3.5 3.5 3.5-1.6 3.5-3.5-1.6-3.5-3.5-3.5z" data-reactid="22"></path></svg>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow-lg" aria-labelledby="dropdown02">
                <h4 class="dropdown-header display-4">Download Pintereso<br/> HTML Bootstrap Template</h4>
                <div class="dropdown-divider">
                </div>
                <span class="dropdown-item"><a href="https://github.com/wowthemesnet/template-pintereso-bootstrap-html/archive/master.zip" class="btn btn-primary d-block"><i class="fa fa-download"></i> Download</a></span>
            </div>
            </li>
        </ul>
    </div>
    </nav> 

    {% block content %}{% endblock content %}

    <script src="{% static 'photo_gallery/assets/js/app.js' %}"></script>
    <script src="{% static 'photo_gallery/assets/js/theme.js' %}"></script>
    
    <footer class="footer pt-5 pb-5 text-center">
        
    <div class="container">
        
          <div class="socials-media">
    
            <ul class="list-unstyled">
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-facebook"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-twitter"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-instagram"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-google-plus"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-behance"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-dribbble"></i></a></li>
            </ul>
    
          </div>
        

          <p>©  <span class="credits font-weight-bold">        
            <a target="_blank" class="text-dark" href="https://www.wowthemes.net/pintereso-free-html-bootstrap-template/"><u>Pintereso Bootstrap HTML Template</u> by WowThemes.net.</a>
          </span>
          </p>
    
    
        </div>
        
    </footer>    
</body>
    
</html>

web/photo_gallery/templates/photo_gallery/index.html
{% extends 'photo_gallery/base.html' %}
{% load static %}


{% block content %}
    <main role="main">
    
    <section class="mt-4 mb-5">
    <div class="container mb-4">
    	<h1 class="font-weight-bold title">Explore</h1>
    	<div class="row">
    		<nav class="navbar navbar-expand-lg navbar-light bg-white pl-2 pr-2">
    		<button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExplore" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
    		</button>
    		<div class="collapse navbar-collapse" id="navbarsExplore">
    			<ul class="navbar-nav">
    				<li class="nav-item">
    				<a class="nav-link" href="#">Lifestyle</a>
    				</li>
    				<li class="nav-item">
    				<a class="nav-link" href="#">Food</a>
    				</li>
    				<li class="nav-item">
    				<a class="nav-link" href="#">Home</a>
    				</li>
    				<li class="nav-item">
    				<a class="nav-link" href="#">Travel</a>
    				</li>
    				<li class="nav-item dropdown">
    				<a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</a>
    				<div class="dropdown-menu shadow-lg" aria-labelledby="dropdown01">
    					<a class="dropdown-item" href="#">Astronomy</a>
    					<a class="dropdown-item" href="#">Nature</a>
    					<a class="dropdown-item" href="#">Cooking</a>
    					<a class="dropdown-item" href="#">Fashion</a>
    					<a class="dropdown-item" href="#">Wellness</a>
    					<a class="dropdown-item" href="#">Dieting</a>
    				</div>
    				</li>
    			</ul>
    		</div>
    		</nav>
    	</div>
    </div>
    <div class="container-fluid">
    	<div class="row">
    		<div class="card-columns">

				{% for post in all_post %}
    			<div class="card card-pin">
    				<img class="card-img" src="{{post.image}}" alt="Card image">
    				<div class="overlay">
    					<h2 class="card-title title">{{ post.title }}</h2>
    					<div class="more">
    						<a href="{% url 'photo_gallery:post' post.slug %}">
    						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
    					</div>
    				</div>
    			</div>
				{% endfor %}

    		</div>
    	</div>
    </div>
    </section>
        
    </main>
{% endblock content %}

web/photo_gallery/templates/photo_gallery/post.html
{% extends 'photo_gallery/base.html' %}
{% load static %}
  
{% block content %}
<main role="main">
    <section class="bg-gray200 pt-5 pb-5">
    <div class="container">
    	<div class="row justify-content-center">
    		<div class="col-md-7">
    			<article class="card">
    			<img class="card-img-top mb-2" src="{{ post.image }}" alt="Card image">
    			<div class="card-body">
    				<h1 class="card-title display-4">
    				{{ post.title }} </h1>
    				{{ post.content| safe }}
    				<small class="d-block"><a class="btn btn-sm btn-gray200" href="{{ post.image }}"><i class="fa fa-external-link"></i> Visit Website</a></small>
    				<!-- Begin Comments -replace demowebsite with your own id
                    ================================================== -->
    				<div id="comments" class="mt-4">
    					<div id="disqus_thread">
    					</div>
    					<script type="text/javascript">
                            var disqus_shortname = 'demowebsite'; 
                            var disqus_developer = 0;
                            (function() {
                                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                                dsq.src = window.location.protocol + '//' + disqus_shortname + '.disqus.com/embed.js';
                                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                            })();
                        </script>
    					<noscript>
    					Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
    					</noscript>
    				</div>
    				<!--End Comments
                    ================================================== -->
    			</div>
    			</article>
    		</div>
    	</div>
    </div>
    <div class="container-fluid mt-5">
    	<div class="row">
    		<h5 class="font-weight-bold">More like this</h5>
    		<div class="card-columns">

				{% for post in random %}
    			<div class="card card-pin">
    				<img class="card-img" src="{{post.image}}" alt="Card image">
    				<div class="overlay">
    					<h2 class="card-title title">{{ post.title }}</h2>
    					<div class="more">
    						<a href="{% url 'photo_gallery:post' post.slug %}">
    						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
    					</div>
    				</div>
    			</div>
				{% endfor %}
    			
    		</div>
    	</div>
    </div>
    </section>
        
    </main>
{% endblock content %}