TOWHIDcv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('enroll/', include('signup_user.urls')),

    # app section
    path('password_generator/', include('app.pass_gen.urls')),
    path('food-app', include('app.food.urls')),
    path('todo/', include('app.todo.urls')),

    # game section
    path('tic-tac-toe', include('game.tic_tac_toe.urls')),
    path('rock-paper-scissors', include('game.rock_paper_scissors.urls')),
    
    # web section
    path('photo-gallery/', include('web.photo_gallery.urls')),
    path('ecommerce/', include('web.ecommerce.urls')),
    path('blog/', include('web.blog.urls')),

    # local
    path('education/', include('education.urls')),

    # Extra
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # app section -- api
    # path('api-auth/', include('rest_framework.urls')),
    path('api/todo/', include('app.todo.api.urls')),
]
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('', views.index, name="index"),
    path('details/<int:pk>', views.details, name="details"),
    path('add', views.add, name="add"),
    path('edit/<int:pk>', views.edit, name="edit"),
    path('delete/<int:pk>', views.delete, name="delete"),
]

index/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index")
]

app/food/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return str(self.item_name)

app/food/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms import widgets
from . models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name',  'item_desc', 'item_price', 'item_image']

        
        labels = {
            'item_name':'Item Name',
            'item_desc': 'Description',
            'item_price': 'Price',
            'item_image': 'Image Link'
        }
    
        widgets = {
            'item_name': forms.TextInput(attrs={'class':'form-control'}),
            'item_desc': forms.TextInput(attrs={'class':'form-control'}),
            'item_price': forms.TextInput(attrs={'class':'form-control'}),
            'item_image': forms.TextInput(attrs={'class':'form-control', 'placeholder':'copy image link and drag'})
        }

app/food/views.py
from django.shortcuts import redirect, render
from . models import Item
from . forms import ItemForm
from django.contrib import messages
# Create your views here.

def index(request):
    item = Item.objects.all()
    return render(request, 'food/index.html', {
        'items': item
    })

def details(request, pk):
    item = Item.objects.get(id=pk)
    return render(request, 'food/details.html', {
        'item': item
    })

def add(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Item Added Succesfully')
            return redirect('food:index')
    else:
        form = ItemForm()
    
    return render(request, 'food/add.html', {
        'form': form
    })


def edit(request, pk):
    item = Item.objects.get(id=pk)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            messages.info(request, 'Item Edit Succesfully')
    else:
        form = ItemForm(instance=item)
    return render(request, 'food/edit.html', {
        'form': form,
        'item': item
    })

def delete(request, pk):
    item = Item.objects.get(id=pk)
    item.delete()
    return redirect('food:index')

app/food/templates/food/add.html
{% extends 'core/core.html' %}
{% load static %}
{% block style %}{% endblock style %}

{% block title %}{% endblock title %}

{% block content %}
    <h2 class="text-center mt-3 alert alert-primary container">Add Item</h2>
    <form action="" method="POST" class="container">
            {% csrf_token %}
            {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }} <br>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-warning">Add</button>
        <a href="{% url 'food:index' %}" class="btn btn-danger">Back</a>
    </form>

    
{% endblock content %}

        
{% block script %}{% endblock script %}

app/food/templates/food/details.html
{% extends 'core/core.html' %}
{% load static %}
{% block style %}{% endblock style %}

{% block title %}{% endblock title %}

{% block content %}
<div class="site-section">
    <div class="container mt-2">

        <div class="card mb-3">
            <img src="{{item.item_image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">#{{item.item_name|slugify}}</h5>
                <p class="card-text">{{item.item_desc}}.</p>
                <p class="card-text"><small class="text-muted">Price: {{item.item_price}}<b class="h4">৳</b> </small></p>
                <p class="card-text"><small class="text-muted">Created: {{item.created|date:"M d, Y"}}</small></p>
            </div>
        </div>

        <a href="{% url 'food:delete' item.id %}" class="btn btn-warning ml-1">Delete</a>
        <a href="{% url 'food:edit' item.id %}" class="btn btn-info ml-1">Edit</a>
        <a href="{% url 'food:index' %}" class="btn btn-danger">Back</a>
    </div>
</div>

{% endblock content %}

        
{% block script %}{% endblock script %}

app/food/templates/food/edit.html
{% extends 'core/core.html' %}
{% load static %}
{% block style %}{% endblock style %}

{% block title %}{% endblock title %}

{% block content %}
    <h2 class="text-center mt-3 alert alert-primary container">Edit {{item.item_name}}</h2>

    {% if messages %}
        {% for message in messages %}
        <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    {% endif %}

    <form action="" method="POST" class="container">
            {% csrf_token %}
            {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }} <br>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-warning">Add</button>
        <a href="{% url 'food:details' item.id %}" class="btn btn-danger">Back</a>
    </form>


{% endblock content %}

        
{% block script %}{% endblock script %}

app/food/templates/food/index.html
{% extends 'core/core.html' %}
{% load static %}
{% block style %} <link rel="stylesheet" href="{% static 'food/css/style.css' %}"> {% endblock style %}

{% block title %}{% endblock title %}

{% block content %}



<div class="container mt-3">

    <div class="row">
      <a href="{% url 'food:add' %}" class="btn btn-outline-danger mb-2">Add</a>
      <a href="/" class="btn btn-outline-secondary mb-2">Home</a>
    </div>

   {% for item in items %}
   <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-4 h-100">
          <img src="{{item.item_image}}" class="img-fluid item-image" alt="">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{item.item_name}}</h5>
            <p class="card-text">{{item.item_desc|truncatechars:70}}</p>
            <a href="{% url 'food:details' item.id %}" class="btn-view mb-1"><span class="ic-sx24"></span>Details</a>
          </div>
        </div>
      </div>
   </div>
   {% endfor %}


     
{% endblock content %}

        
{% block script %}{% endblock script %}