TOWHIDcv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('enroll/', include('signup_user.urls')),

    # app section
    path('password_generator/', include('app.pass_gen.urls')),
    path('food-app', include('app.food.urls')),
    path('todo/', include('app.todo.urls')),

    # game section
    path('tic-tac-toe', include('game.tic_tac_toe.urls')),
    path('rock-paper-scissors', include('game.rock_paper_scissors.urls')),
    
    # web section
    path('photo-gallery/', include('web.photo_gallery.urls')),
    path('ecommerce/', include('web.ecommerce.urls')),
    path('blog/', include('web.blog.urls')),

    # local
    path('education/', include('education.urls')),

    # Extra
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # app section -- api
    # path('api-auth/', include('rest_framework.urls')),
    path('api/todo/', include('app.todo.api.urls')),
]
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education/urls.py
from django.urls import path
from . import views

app_name = 'education'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:slug>', views.details, name="details")
]

index/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index")
]

education/models.py
from django.db import models
import re
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.

# Remove HTML tags and return clean string text
CLEANR = re.compile('<[^>]*>') 
def cleanhtml(raw_html):
  cleantext = re.sub(CLEANR, '', raw_html)
  return cleantext

class Subject(models.Model):
    title = models.CharField(max_length=100)
    small_disc = RichTextField()
    image_URL = models.ImageField(upload_to='subjects', help_text='the image should be 600x300')
    disc = RichTextField()
    site_title = models.CharField(max_length=100, blank=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Subject, self).save(*args, **kwargs)


    def __str__(self):
        return self.title

class Middle_text(models.Model):
    text = RichTextField()
    def __str__(self):
        return cleanhtml(self.text[0:60])

class Gallery(models.Model):
    image = models.CharField(max_length=500, help_text='The image should be 450x300 && put "coppy image address" here.')

    def __str__(self):
        return self.image[0:60]

education/views.py
from django.shortcuts import render
from . models import Subject, Gallery, Middle_text

# Create your views here.

def index(request):
    sub_data = Subject.objects.all()
    images = Gallery.objects.all()
    text = Middle_text.objects.first()
    return render(request, 'education/index.html', {
        'sub_data':sub_data,
        'images':images,
        'text': text
    })

def details(request, slug):
    sub_data = Subject.objects.get(slug=slug)
    return render(request, 'education/columns.html', {
        'sub_data':sub_data
    })

education/templates/education/base.html
{% load static %}
<head>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}
    <title>Start Your Favourite Courses Online</title>
    {% endblock title %}
<!--
Lumino Theme
http://www.templatemo.com/tm-483-lumino
-->
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:100,300,400">   <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="{% static 'education/font-awesome-4.5.0/css/font-awesome.min.css' %}">                <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'education/css/bootstrap.min.css' %}">                                      <!-- Bootstrap style -->
    <link rel="stylesheet" href="{% static 'education/css/magnific-popup.css' %}">                                     <!-- Magnific pop up style -->
    <link rel="stylesheet" href="{% static 'education/css/templatemo-style.css' %}">  
    {% block link %}{% endblock link %}                             <!-- Templatemo style -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
</head>

{% block body %}{% endblock body %}



<!-- load JS files -->
    <script src="{% static 'education/js/jquery-1.11.3.min.js' %}"></script>             <!-- jQuery (https://jquery.com/download/) -->
    <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap, http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h --> 
    <script src="{% static 'education/js/bootstrap.min.js' %}"></script>                 <!-- Bootstrap (http://v4-alpha.getbootstrap.com/) -->
    <script src="{% static 'education/js/jquery.singlePageNav.min.js' %}"></script>      <!-- Single Page Nav (https://github.com/ChrisWojcik/single-page-nav) -->
    <script src="{% static 'education/js/jquery.magnific-popup.min.js' %}"></script>     <!-- Magnific pop-up (http://dimsemenov.com/plugins/magnific-popup/) -->

{% block scripts %}{% endblock scripts %}
</html>

education/templates/education/columns.html
{% extends 'education/base.html' %}
{% load static %}
{% load social_share %}

{% block title %}
    <title>{{sub_data.site_title}}</title>
{% endblock title %}

{% block link %}<link rel="stylesheet" href="{% static 'education/css/style.css' %}">  {% endblock link %}

{% block body %}
    <body id="top" class="page-2">

        <div class="tm-navbar-container tm-navbar-container-dark">
       
            <nav class="navbar navbar-full navbar-fixed-top bg-inverse">
                <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                    &#9776;
                </button>
                <div class="collapse navbar-toggleable-sm" id="tmNavbar">
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'education:index' %}" class="nav-link external">Home</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

        <div class="terb">
            {% post_to_facebook object_or_url " " "fa fa-facebook" %}
    
            {% post_to_twitter "{{sub_data.small_disc|safe}}" object_or_url " " "fa fa-twitter" %}

            {% post_to_linkedin object_or_url "fab fa-linkedin-in" %}

            {% post_to_whatsapp object_or_url " " "fa fa-whatsapp" %}

            {% post_to_telegram "{{sub_data.small_disc|safe}}" object_or_url " " "fa fa-paper-plane" %}
        </div>

    
        <div class="container-fluid">

            <div class="row">
              <div id="tm-section-1" class="tm-section">
                <div class="col-md-12">
                    <h1 class="text-xs-center blue-text tm-page-2-title">{{sub_data.title|upper}}</h1>
                    <p class="text-xs-center tm-page-2-p tm-page-2-subtitle">{{sub_data.small_disc|safe}}</p>
                    <img src="{{sub_data.image_URL.url}}" class="img-fluid tm-banner-img" alt="Image">            
                </div>
              </div>                
            </div>
            
            <div class="row">
                <div class="tm-section" id="tm-section-2">
                    <div class="col-md-12">
                        <p class="text-left tm-description">{{sub_data.disc|safe}}</p>
                        
                        <div class="tm-flex-center">
                          <a href="#" class="btn btn-default btn-lg tm-gray-btn back-btn">Back</a>
                          
                        </div>
                    </div>
                </div>
            </div>

            <br><br>
      
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <p class="text-xs-center tm-footer-text">Copyright &copy; TOWHIDpro</p>
                </div>
            </div>
        </div>
    </body>
{% endblock body %}

{% block scripts %}
<script>
    document.querySelector('.back-btn').addEventListener('click', goBack)
    function goBack() {
        window.history.back();
    }
</script>
{% endblock scripts %}

education/templates/education/index.html
{% extends 'education/base.html' %}
{% load static %}



{% block body %}
    <body id="top" class="home">
       
        <div class="container-fluid">
            <div class="row">
              
                <div class="tm-navbar-container">
                
                <!-- navbar   -->
                <nav class="navbar navbar-full navbar-fixed-top">

                    <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                        &#9776;
                    </button>
                        
                    <div class="collapse navbar-toggleable-sm" id="tmNavbar">                            

                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#top">UP</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#tm-section-2">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#tm-section-3">Gallery</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link external" href="/">Tutor</a>
                            </li>
                        </ul>

                    </div>
                  
                </nav>

              </div>  

           </div>

           <div class="row">
                <div class="tm-intro">

                    <section id="tm-section-1">                        
                        <div class="tm-container text-xs-center tm-section-1-inner">
                            <img src="{% static 'education/img/python.png' %}" alt="Logo" class="tm-logo" height="200px">
                            <h1 class="tm-site-name" style="color: rgb(250, 3, 3);">START</h1>
                            <p class="tm-intro-text" style="color: rgb(255, 251, 0);">Your Favourite</p>
                            <a href="#tm-section-2" class="tm-intro-link">Courses</a>    
                        </div>                                               
                   </section>

                </div>
            </div>

            <div class="row gray-bg">
                
                <div id="tm-section-2" class="tm-section">
                    <div class="tm-container tm-container-wide">
                        {% for sub_dta in sub_data %}
                        <div class="tm-news-item">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-news-item-img-container{% if forloop.counter|divisibleby:2 %}
                            flex-order-2{% endif %}">
                                <img src="{{sub_dta.image_URL.url}}" alt="Image" class="img-fluid tm-news-item-img">  
                            </div>
                            
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-news-container">
                                <h2 class="tm-news-title dark-gray-text">{{sub_dta.title|upper}}</h2>
                                <p class="tm-news-text">{{sub_dta.small_disc|safe|truncatechars:200}}</p>
                                <a href="{% url 'education:details' sub_dta.slug %}" class="btn tm-light-blue-bordered-btn tm-news-link">Preview</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>                    
               </div>

           </div> <!-- row -->

            <div class="row">

                <section id="tm-section-3" class="tm-section">
                    <div class="tm-container text-xs-center">
                        
                        <h2 class="blue-text tm-title">{{text.text|safe}}</h2>
                       
                        <div class="tm-img-grid">
                            {% for img in images %}
                            <div class="tm-gallery-img-container">
                                <a href="{{img.image}}" class="tm-gallery-img-link">
                                    <img src="{{img.image}}" alt="Image" class="img-fluid tm-gallery-img">
                                </a>
                            </div>
                            {% endfor %}

                        </div>
                    </div>
                </section>

            </div> <!-- row -->

            <div class="row gray-bg">

                <!-- footer -->
                <footer class="tm-footer">                
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <p class="text-xs-center tm-footer-text">Copyright &copy; TOWHIDpro</p>                    
                    </div>                
                </footer>  

            </div> <!-- row -->
           
        </div> <!-- container-fluid -->           

</body>
{% endblock body %}

{% block scripts %}
<!-- Templatemo scripts -->
<script>     

    $(document).ready(function(){
        var mobileTopOffset = 54;
        var desktopTopOffset = 80;
        var topOffset = desktopTopOffset;
        if($(window).width() <= 767) {
            topOffset = mobileTopOffset;
        }
        
        /* Single page nav
        -----------------------------------------*/
        $('#tmNavbar').singlePageNav({
           'currentClass' : "active",
            offset : topOffset,
            'filter': ':not(.external)'
        }); 
        /* Handle nav offset upon window resize
        -----------------------------------------*/
        $(window).resize(function(){
            if($(window).width() <= 767) {
                topOffset = mobileTopOffset;
            } 
            else {
                topOffset = desktopTopOffset;
            }
            $('#tmNavbar').singlePageNav({
                'currentClass' : "active",
                offset : topOffset,
                'filter': ':not(.external)'
            });
        });
        
        /* Collapse menu after click 
        -----------------------------------------*/
        $('#tmNavbar a').click(function(){
            $('#tmNavbar').collapse('hide');
        });
        /* Turn navbar background to solid color starting at section 2
        ---------------------------------------------------------------*/
        var target = $("#tm-section-2").offset().top - topOffset;
        if($(window).scrollTop() >= target) {
            $(".tm-navbar-container").addClass("bg-inverse");
        }
        else {
            $(".tm-navbar-container").removeClass("bg-inverse");
        }
        $(window).scroll(function(){
           
            if($(this).scrollTop() >= target) {
                $(".tm-navbar-container").addClass("bg-inverse");
            }
            else {
                $(".tm-navbar-container").removeClass("bg-inverse");
            }
        });
        /* Smooth Scrolling
         * https://css-tricks.com/snippets/jquery/smooth-scrolling/
        --------------------------------------------------------------*/
        $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
                && location.hostname == this.hostname) {
                
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                
                if (target.length) {
                    
                    $('html, body').animate({
                        scrollTop: target.offset().top - topOffset
                    }, 1000);
                    return false;
                }
            }
        }); 
      
        /* Magnific pop up
        ------------------------- */
        $('.tm-img-grid').magnificPopup({
            delegate: 'a', // child items selector, by clicking on it popup will open
            type: 'image',
            gallery: {enabled:true}            
        });            
    });
</script> 
{% endblock scripts %} 